### ISSUE TITLE
Suggestion: Structure app to hide stuff from web root

### ISSUE THREAD

**Issue by paragonie-scott** [spanishtech/Live-CMS#3]
For better security, instead of 
- content/
- inc/
- install/
- lib/
- LICENSE
- README.md
- footer.php
- header.php
- index.php

I would suggest moving the landing point to a subdirectory (e.g. public), and help users set their virtualhost's document root to point to that subdirectory.
- content/
- inc/
- install/
- lib/
- public/
  - css/
  - images/
  - js/
  - index.php
- LICENSE
- README.md
- footer.php
- header.php

This would reduce the chance of people accidentally dropping something sensitive into a directory that is accessible by the webserver (i.e. Apache).

**Comment by spanishtech** [comment]
I've been really busy lately but when i get around to it I'll do that.

**Comment by paragonie-scott** [comment]
I understand. Take your time. :)

**Comment by spanishtech** [comment]
Starting this entire thing from scratch and will be implementing this.
